name: beta_lister
description: List available beta apps on Android.
version: 0.3.3+11

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  device_apps: ^1.0.9
  url_launcher: ^5.4.5
  dio: ^3.0.8
  flutter_i18n: ^0.14.0
  intro_views_flutter: ^2.8.1
  shared_preferences: ^0.5.7+1
  firebase_analytics: ^5.0.10
  firebase_crashlytics: ^0.1.2+4

dev_dependencies:
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/onboarding/
