name: beta_lister
description: List available beta apps on Android.
version: 0.2.3+6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  device_apps: ^1.0.8
  url_launcher: ^5.0.3
  cloud_functions: ^0.4.0+1
  flutter_i18n: ^0.6.3
  intro_views_flutter: ^2.6.0
  shared_preferences: ^0.5.3+1
  flutter_launcher_icons: ^0.7.2
  firebase_analytics: ^3.0.2

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/onboarding/
