name: beta_lister
description: List available beta apps on Android.
version: 0.2.4+7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  device_apps: ^1.0.8
  url_launcher: ^5.2.5
  dio: ^3.0.3
  flutter_i18n: ^0.7.0
  intro_views_flutter: ^2.8.0
  shared_preferences: ^0.5.4+1
  flutter_launcher_icons: ^0.7.3
  firebase_analytics: ^5.0.2

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/onboarding/
