name: beta_lister
description: List available beta apps on Android.
version: 0.3.0+8

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  device_apps: ^1.0.9
  url_launcher: ^5.4.1
  dio: ^3.0.8
  flutter_i18n: ^0.8.3
  intro_views_flutter: ^2.8.0
  shared_preferences: ^0.5.6+1
  flutter_launcher_icons: ^0.7.4
  firebase_analytics: ^5.0.10
  firebase_crashlytics: ^0.1.2+4

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/onboarding/
